package Final_ST2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.math.BigInteger;
import java.security.SecureRandom;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author kiddabove
 */
public class AddEmployee extends javax.swing.JFrame {
        Connection conn = new DBConnection().connect();
        commonFunctions validations = new commonFunctions();
    
    public AddEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ADD_EMPLOYEE = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        EMPLOYEE_EMAIL = new javax.swing.JTextField();
        EMPLOYEE_YOB = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EMPLOYEE_NIC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EMPLOYEE_NAME = new javax.swing.JTextField();
        EMPLOYEE_PASSWORD = new javax.swing.JTextField();
        EMPLOYEE_EID = new javax.swing.JTextField();
        EMPLOYEE_CONTACT_NUMBER = new javax.swing.JTextField();
        EMPLOYEE_DOB = new javax.swing.JComboBox();
        EMPLOYEE_ADDRESS1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EMPLOYEE_USERNAME = new javax.swing.JTextField();
        GENERATE_PASSWORD = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EMPLOYEE_MOB = new javax.swing.JComboBox();
        EMPLOYEE_DESIGNATION = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD NEW EMPLOYEE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 10, 254, 29);

        ADD_EMPLOYEE.setText("ADD EMPLOYEE");
        ADD_EMPLOYEE.setPreferredSize(new java.awt.Dimension(145, 30));
        ADD_EMPLOYEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_EMPLOYEEActionPerformed(evt);
            }
        });
        jPanel1.add(ADD_EMPLOYEE);
        ADD_EMPLOYEE.setBounds(80, 610, 145, 30);

        CANCEL.setText("CANCEL");
        CANCEL.setPreferredSize(new java.awt.Dimension(145, 30));
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });
        jPanel1.add(CANCEL);
        CANCEL.setBounds(420, 610, 145, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("PASSWORD");
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 540, 150, 30);

        EMPLOYEE_EMAIL.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_EMAIL.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EMPLOYEE_EMAIL);
        EMPLOYEE_EMAIL.setBounds(280, 340, 294, 30);

        EMPLOYEE_YOB.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_YOB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900", "1899", "1898", "1897", "1896", "1895", "1894", "1893", "1892", "1891", "1890", "1889", "1888", "1887", "1886", "1885", "1884", "1883", "1882", "1881", "1880", "1879", "1878", "1877", "1876", "1875", "1874", "1873", "1872", "1871", "1870", "1869", "1868", "1867", "1866", "1865", "1864", "1863", "1862", "1861", "1860", "1859", "1858", "1857", "1856", "1855", "1854", "1853", "1852", "1851", "1850", "1849", "1848", "1847", "1846", "1845", "1844", "1843", "1842", "1841", "1840", "1839", "1838", "1837", "1836", "1835", "1834", "1833", "1832", "1831", "1830", "1829", "1828", "1827", "1826", "1825", "1824", "1823", "1822", "1821", "1820", "1819", "1818", "1817" }));
        EMPLOYEE_YOB.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(EMPLOYEE_YOB);
        EMPLOYEE_YOB.setBounds(490, 300, 80, 25);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("BIRTHDAY");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 300, 150, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("CONTACT NUMBER");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 440, 150, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("NAME");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 140, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("USER NAME");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 490, 150, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("EMAIL");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 340, 150, 30);

        EMPLOYEE_NIC.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_NIC.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EMPLOYEE_NIC);
        EMPLOYEE_NIC.setBounds(280, 190, 294, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("NIC");
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 190, 150, 30);

        EMPLOYEE_NAME.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_NAME.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EMPLOYEE_NAME);
        EMPLOYEE_NAME.setBounds(280, 140, 294, 30);

        EMPLOYEE_PASSWORD.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_PASSWORD.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(EMPLOYEE_PASSWORD);
        EMPLOYEE_PASSWORD.setBounds(280, 540, 120, 30);

        EMPLOYEE_EID.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_EID.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EMPLOYEE_EID);
        EMPLOYEE_EID.setBounds(280, 90, 294, 30);

        EMPLOYEE_CONTACT_NUMBER.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_CONTACT_NUMBER.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EMPLOYEE_CONTACT_NUMBER);
        EMPLOYEE_CONTACT_NUMBER.setBounds(280, 440, 294, 30);

        EMPLOYEE_DOB.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_DOB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        EMPLOYEE_DOB.setPreferredSize(new java.awt.Dimension(50, 30));
        EMPLOYEE_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPLOYEE_DOBActionPerformed(evt);
            }
        });
        jPanel1.add(EMPLOYEE_DOB);
        EMPLOYEE_DOB.setBounds(280, 300, 73, 25);

        EMPLOYEE_ADDRESS1.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_ADDRESS1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EMPLOYEE_ADDRESS1);
        EMPLOYEE_ADDRESS1.setBounds(280, 390, 294, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("ADDRESS");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 390, 150, 30);

        EMPLOYEE_USERNAME.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_USERNAME.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EMPLOYEE_USERNAME);
        EMPLOYEE_USERNAME.setBounds(280, 490, 294, 30);

        GENERATE_PASSWORD.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        GENERATE_PASSWORD.setText("GENERATE PASSWORD");
        GENERATE_PASSWORD.setPreferredSize(new java.awt.Dimension(150, 30));
        GENERATE_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENERATE_PASSWORDActionPerformed(evt);
            }
        });
        jPanel1.add(GENERATE_PASSWORD);
        GENERATE_PASSWORD.setBounds(420, 540, 150, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("EID");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 90, 150, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("DESIGNATION");
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 250, 150, 30);

        EMPLOYEE_MOB.setBackground(new java.awt.Color(204, 204, 204));
        EMPLOYEE_MOB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        EMPLOYEE_MOB.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(EMPLOYEE_MOB);
        EMPLOYEE_MOB.setBounds(380, 300, 81, 25);

        EMPLOYEE_DESIGNATION.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EMPLOYEE_DESIGNATION.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Admin", "Receptionist" }));
        jPanel1.add(EMPLOYEE_DESIGNATION);
        EMPLOYEE_DESIGNATION.setBounds(280, 240, 294, 41);

        jButton1.setText("RESET");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 610, 100, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/addEmployee.png"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(610, 670));
        jPanel1.add(Background);
        Background.setBounds(0, -20, 630, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADD_EMPLOYEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_EMPLOYEEActionPerformed

        String EID = validations.getTextValue(EMPLOYEE_EID);
        String ENAME = validations.getTextValue(EMPLOYEE_NAME);
        String NIC = validations.getTextValue(EMPLOYEE_NIC);
        String DESIGNATION = validations.getJComboBoxValue(EMPLOYEE_DESIGNATION);
        String DOB = validations.getJComboBoxValue(EMPLOYEE_DOB);
        String MOB = validations.getJComboBoxValue(EMPLOYEE_MOB);
        String YOB = validations.getJComboBoxValue(EMPLOYEE_YOB);
        String EMAIL = validations.getTextValue(EMPLOYEE_EMAIL);
        String ADDRESS = validations.getTextValue(EMPLOYEE_USERNAME);
        String CONTACT_NUMBER = validations.getTextValue(EMPLOYEE_CONTACT_NUMBER);
        String USERNAME = validations.getTextValue(EMPLOYEE_USERNAME);
        String PASSWORD = validations.getTextValue(EMPLOYEE_PASSWORD);
        
        
        if(EID.equals("") ||ENAME.equals("") ||NIC.equals("") ||DESIGNATION.equals("")    ||DOB.equals("") ||MOB.equals("") ||YOB.equals("") ||EMAIL.equals("") ||ADDRESS.equals("")||CONTACT_NUMBER.equals("") ||USERNAME.equals("") ||PASSWORD.equals("") ){
            validations.EmptyForm();
        }

        else{
           
            PreparedStatement ps = null; 
            try{
                ps =conn.prepareStatement("insert into Employee values(?,?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1, EID);
                ps.setString(2, ENAME);
                ps.setString(3, NIC);
                ps.setString(4, DESIGNATION);
                ps.setString(5, DOB);
                ps.setString(6, MOB);
                ps.setString(7, YOB);
                ps.setString(8, EMAIL);
                ps.setString(9, ADDRESS);
                ps.setString(10, CONTACT_NUMBER);
                ps.setString(11, USERNAME);
                ps.setString(12, PASSWORD);

                    int i = ps.executeUpdate();

                    if(i>0){
                        JOptionPane.showMessageDialog(null, "Data Successfully Entered into Database");   
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Data not Entered into Database");
                    }

                            
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);

            }
        }
        

    }//GEN-LAST:event_ADD_EMPLOYEEActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
         dispose();
    }//GEN-LAST:event_CANCELActionPerformed

    private void GENERATE_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENERATE_PASSWORDActionPerformed
        final SecureRandom random = new SecureRandom();
         String passwordString = new BigInteger(50, random).toString(32);
         EMPLOYEE_PASSWORD.setText(passwordString);
    }//GEN-LAST:event_GENERATE_PASSWORDActionPerformed

    private void EMPLOYEE_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPLOYEE_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMPLOYEE_DOBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       EMPLOYEE_EID.setText("");
       EMPLOYEE_NAME.setText("");
       EMPLOYEE_NIC.setText("");
       EMPLOYEE_DESIGNATION.setSelectedItem(null);
       EMPLOYEE_DOB.setSelectedItem(null);
       EMPLOYEE_MOB.setSelectedItem(null);
       EMPLOYEE_YOB.setSelectedItem(null);
       EMPLOYEE_EMAIL.setText("");
       EMPLOYEE_USERNAME.setText("");
       EMPLOYEE_CONTACT_NUMBER.setText("");
       EMPLOYEE_USERNAME.setText("");
       EMPLOYEE_PASSWORD.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_EMPLOYEE;
    private javax.swing.JLabel Background;
    private javax.swing.JButton CANCEL;
    private javax.swing.JTextField EMPLOYEE_ADDRESS1;
    private javax.swing.JTextField EMPLOYEE_CONTACT_NUMBER;
    private javax.swing.JComboBox EMPLOYEE_DESIGNATION;
    private javax.swing.JComboBox EMPLOYEE_DOB;
    private javax.swing.JTextField EMPLOYEE_EID;
    private javax.swing.JTextField EMPLOYEE_EMAIL;
    private javax.swing.JComboBox EMPLOYEE_MOB;
    private javax.swing.JTextField EMPLOYEE_NAME;
    private javax.swing.JTextField EMPLOYEE_NIC;
    private javax.swing.JTextField EMPLOYEE_PASSWORD;
    private javax.swing.JTextField EMPLOYEE_USERNAME;
    private javax.swing.JComboBox EMPLOYEE_YOB;
    private javax.swing.JButton GENERATE_PASSWORD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
