package Final_ST2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;


/**
 *
 * @author Yaseer
 */
public class DeleteEmployee extends javax.swing.JFrame {
     Connection conn = new DBConnection().connect();
     commonFunctions validations = new commonFunctions();
    /**
     * Creates new form deleteCustomer
     */
    public DeleteEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        Emp_ID = new javax.swing.JTextField();
        CloseFrame = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        RESET = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Delete.setText("Delete");
        Delete.setPreferredSize(new java.awt.Dimension(60, 30));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(61, 122, 70, 31);

        Emp_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_IDActionPerformed(evt);
            }
        });
        jPanel1.add(Emp_ID);
        Emp_ID.setBounds(124, 69, 200, 35);

        CloseFrame.setText("Close");
        CloseFrame.setPreferredSize(new java.awt.Dimension(80, 30));
        CloseFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFrameActionPerformed(evt);
            }
        });
        jPanel1.add(CloseFrame);
        CloseFrame.setBounds(237, 122, 70, 31);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Delete Employee ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(78, 11, 200, 28);

        RESET.setText("Reset");
        RESET.setPreferredSize(new java.awt.Dimension(60, 30));
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel1.add(RESET);
        RESET.setBounds(149, 122, 70, 31);

        jLabel1.setText("Employee ID");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 79, 80, 30);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 70, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
            
        if(validations.isEmpty(validations.getTextValue(Emp_ID))){
            validations.EmptyForm();
        }
        else{
            String EID = Emp_ID.getText();
            int dialogResult = JOptionPane.showConfirmDialog(this, "Delete Employee ?", "delete'"+EID+"'?", JOptionPane.YES_NO_OPTION);
            if (dialogResult == 0) {
                try{
                    Statement stmt = conn.createStatement();
                    String query = "SELECT * FROM Employee WHERE eid = '"+Emp_ID.getText()+"' ";
                    ResultSet rs = stmt.executeQuery(query);
                    String eid = null;
                    if(rs.next()){
                        eid = (rs.getString(1));
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Employee not found");
                    }

                    if(Emp_ID.getText().equals("") || !Emp_ID.getText().equals(eid))
                          Emp_ID.setText("Enter Correct EID..!");
                    else{
                    String sql = "DELETE FROM Employee WHERE eid = '"+Emp_ID.getText()+"' ";
                    stmt.execute(sql);


                    JOptionPane.showMessageDialog(this, "Employee Deleted Successfully");
                    }   

                 } 
                catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
            else { 
                System.out.println("Deletion Aborted");
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void Emp_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_IDActionPerformed
            
    }//GEN-LAST:event_Emp_IDActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        Emp_ID.setText("");
    }//GEN-LAST:event_RESETActionPerformed

    private void CloseFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseFrameActionPerformed
        dispose();
    }//GEN-LAST:event_CloseFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseFrame;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Emp_ID;
    private javax.swing.JButton RESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
