package Final_ST2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yaseer
 */
public class MainMenu_for_Manager extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu_for_Manager
     */
    public MainMenu_for_Manager() {
        initComponents();
         // Set the JFrame to maximize by default on opening
       //setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteEmp = new javax.swing.JLabel();
        Delete_EMPLOYEE = new javax.swing.JButton();
        Customer = new javax.swing.JLabel();
        CUSTOMER_DETAILS = new javax.swing.JButton();
        reserve = new javax.swing.JLabel();
        Reservation_List = new javax.swing.JButton();
        SearchEmp = new javax.swing.JLabel();
        SEARCH_EMPLOYEE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Update_Button = new javax.swing.JButton();
        LogOUT = new javax.swing.JLabel();
        AddEmp = new javax.swing.JLabel();
        Add_Employee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reportss = new javax.swing.JLabel();
        REPORTS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MainMenu_Manager = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        deleteEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/DeleteEmp.png"))); // NOI18N
        jPanel1.add(deleteEmp);
        deleteEmp.setBounds(580, 330, 65, 65);

        Delete_EMPLOYEE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete_EMPLOYEE.setText("Delete Employee");
        Delete_EMPLOYEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_EMPLOYEEActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_EMPLOYEE);
        Delete_EMPLOYEE.setBounds(410, 360, 200, 40);

        Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/CustomerSmall.png"))); // NOI18N
        jPanel1.add(Customer);
        Customer.setBounds(280, 100, 65, 65);

        CUSTOMER_DETAILS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CUSTOMER_DETAILS.setText("View Customer Details");
        CUSTOMER_DETAILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUSTOMER_DETAILSActionPerformed(evt);
            }
        });
        jPanel1.add(CUSTOMER_DETAILS);
        CUSTOMER_DETAILS.setBounds(100, 120, 200, 40);

        reserve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/ReservationList.png"))); // NOI18N
        jPanel1.add(reserve);
        reserve.setBounds(260, 210, 65, 65);

        Reservation_List.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Reservation_List.setText("Reservation List");
        Reservation_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reservation_ListActionPerformed(evt);
            }
        });
        jPanel1.add(Reservation_List);
        Reservation_List.setBounds(100, 240, 200, 40);

        SearchEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/SearchEmp.png"))); // NOI18N
        jPanel1.add(SearchEmp);
        SearchEmp.setBounds(580, 90, 65, 65);

        SEARCH_EMPLOYEE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SEARCH_EMPLOYEE.setText("Search Employee");
        SEARCH_EMPLOYEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_EMPLOYEEActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH_EMPLOYEE);
        SEARCH_EMPLOYEE.setBounds(410, 120, 200, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/UpdateEmp.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(570, 220, 65, 65);

        Update_Button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update_Button.setText("Update Employee");
        Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Update_Button);
        Update_Button.setBounds(410, 250, 200, 40);

        LogOUT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogOUT.setText("Log Out");
        LogOUT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, null, java.awt.Color.darkGray));
        LogOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOUTMouseClicked(evt);
            }
        });
        jPanel1.add(LogOUT);
        LogOUT.setBounds(690, 0, 60, 30);

        AddEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/EmployeeAdd.png"))); // NOI18N
        jPanel1.add(AddEmp);
        AddEmp.setBounds(260, 330, 65, 65);

        Add_Employee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Add_Employee.setText("Add Employee");
        Add_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_EmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Employee);
        Add_Employee.setBounds(100, 360, 200, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/welcomeNote.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 0, 447, 33);

        reportss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/report.png"))); // NOI18N
        jPanel1.add(reportss);
        reportss.setBounds(430, 420, 65, 65);

        REPORTS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        REPORTS.setText("View Reports");
        REPORTS.setPreferredSize(new java.awt.Dimension(200, 40));
        REPORTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTSActionPerformed(evt);
            }
        });
        jPanel1.add(REPORTS);
        REPORTS.setBounds(280, 430, 200, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Login As Manager ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 30, 100, 20);

        MainMenu_Manager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/ManagerHome.png"))); // NOI18N
        jPanel1.add(MainMenu_Manager);
        MainMenu_Manager.setBounds(0, 0, 750, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Delete_EMPLOYEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_EMPLOYEEActionPerformed
        DeleteEmployee Del_Emp = new DeleteEmployee();
        Del_Emp.setVisible(true);
    }//GEN-LAST:event_Delete_EMPLOYEEActionPerformed

    private void CUSTOMER_DETAILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUSTOMER_DETAILSActionPerformed
        CustomerDetails customer = new CustomerDetails();
       customer.setVisible(true);
        
    }//GEN-LAST:event_CUSTOMER_DETAILSActionPerformed

    private void SEARCH_EMPLOYEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_EMPLOYEEActionPerformed
        
        try {
            SearchEmployee searchEmp = new SearchEmployee();
            searchEmp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu_for_Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
   
       
    }//GEN-LAST:event_SEARCH_EMPLOYEEActionPerformed

    private void Add_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_EmployeeActionPerformed
        AddEmployee add = new AddEmployee();
        add.setVisible(true);
    }//GEN-LAST:event_Add_EmployeeActionPerformed

    private void LogOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOUTMouseClicked
       Login login = new Login();
       login.setVisible(true);
       dispose();
    }//GEN-LAST:event_LogOUTMouseClicked

    private void Reservation_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reservation_ListActionPerformed
        Reservation_List list = new Reservation_List();
       list.setVisible(true);
    }//GEN-LAST:event_Reservation_ListActionPerformed

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
        UpdateEmployee updateEmp = new UpdateEmployee();
        updateEmp.setVisible(true);
    }//GEN-LAST:event_Update_ButtonActionPerformed

    private void REPORTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTSActionPerformed
        Report re = new Report();
        re.setVisible(true);
    }//GEN-LAST:event_REPORTSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_for_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_for_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_for_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_for_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_for_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddEmp;
    private javax.swing.JButton Add_Employee;
    private javax.swing.JButton CUSTOMER_DETAILS;
    private javax.swing.JLabel Customer;
    private javax.swing.JButton Delete_EMPLOYEE;
    private javax.swing.JLabel LogOUT;
    private javax.swing.JLabel MainMenu_Manager;
    private javax.swing.JButton REPORTS;
    private javax.swing.JButton Reservation_List;
    private javax.swing.JButton SEARCH_EMPLOYEE;
    private javax.swing.JLabel SearchEmp;
    private javax.swing.JButton Update_Button;
    private javax.swing.JLabel deleteEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel reportss;
    private javax.swing.JLabel reserve;
    // End of variables declaration//GEN-END:variables
}
