package Final_ST2;


import java.util.HashMap;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yaseer
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RoomTypeID = new javax.swing.JTextField();
        Close = new javax.swing.JButton();
        roomAndRoomType = new javax.swing.JButton();
        employee = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        customer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        customer.setText("Full Customer Details");
        customer.setPreferredSize(new java.awt.Dimension(250, 45));
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer);
        customer.setBounds(210, 210, 250, 48);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("GENERATE  REPORTS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 0, 220, 49);

        RoomTypeID.setBackground(new java.awt.Color(0, 204, 204));
        RoomTypeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeIDActionPerformed(evt);
            }
        });
        jPanel1.add(RoomTypeID);
        RoomTypeID.setBounds(70, 310, 103, 40);

        Close.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close);
        Close.setBounds(440, 430, 100, 30);

        roomAndRoomType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        roomAndRoomType.setText("View Room & Room_Type");
        roomAndRoomType.setPreferredSize(new java.awt.Dimension(250, 45));
        roomAndRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomAndRoomTypeActionPerformed(evt);
            }
        });
        jPanel1.add(roomAndRoomType);
        roomAndRoomType.setBounds(210, 310, 250, 45);

        employee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        employee.setText("Full Employee Details");
        employee.setPreferredSize(new java.awt.Dimension(250, 45));
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jPanel1.add(employee);
        employee.setBounds(210, 100, 250, 48);

        jLabel3.setBackground(new java.awt.Color(102, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ROOM TYPE ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 350, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/reportIcon.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 50, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/reportLabel.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 50, 460, 360);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/reportss.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 540, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void RoomTypeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTypeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomTypeIDActionPerformed

    private void roomAndRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomAndRoomTypeActionPerformed
        if(RoomTypeID.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Please Enter Room Type ID");
        
        }else
            {
            HashMap para = new HashMap();
            if(RoomTypeID.getText().length() != 0){

                para.put("roomTypeId",RoomTypeID.getText());
                JReportViewer rp = new JReportViewer("./report/assignRoomType.jasper", para);
                rp.setVisible(true);

            }
        }
    }//GEN-LAST:event_roomAndRoomTypeActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        JReportViewer r = new JReportViewer("./report/customer.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_customerActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        JReportViewer r = new JReportViewer("./report/employee.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_employeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Close;
    private javax.swing.JTextField RoomTypeID;
    private javax.swing.JButton customer;
    private javax.swing.JButton employee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton roomAndRoomType;
    // End of variables declaration//GEN-END:variables
}
