package Final_ST2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yaseer
 */
public class SearchCustomer extends javax.swing.JFrame {

   
    
    public SearchCustomer() {
        initComponents();
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CUSTOMER_NIC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CUSTOMER_CITY = new javax.swing.JLabel();
        CUSTOMER_STATUS = new javax.swing.JLabel();
        CUSTOMER_ADDRESS = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CUSTOMER_AGE = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CUSTOMER_L_NAME = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CUSTOMER_F_NAME = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CUSTOMER_CONTACT_NUMBER = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CUSTOMER_EMAIL = new javax.swing.JLabel();
        CUSTOMER_GENDER = new javax.swing.JLabel();
        BACK_BUTTON = new javax.swing.JButton();
        CUSTOMER_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Details");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Status");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Selected Customer ID");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("First Name");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Last Name");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 25));

        CUSTOMER_NIC.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_NIC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_NIC.setText("NaN");
        CUSTOMER_NIC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_NIC.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Age");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 25));

        CUSTOMER_CITY.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_CITY.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_CITY.setText("NaN");
        CUSTOMER_CITY.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_CITY.setPreferredSize(new java.awt.Dimension(170, 25));

        CUSTOMER_STATUS.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_STATUS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_STATUS.setText("NaN");
        CUSTOMER_STATUS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_STATUS.setPreferredSize(new java.awt.Dimension(170, 25));

        CUSTOMER_ADDRESS.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_ADDRESS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_ADDRESS.setText("NaN");
        CUSTOMER_ADDRESS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_ADDRESS.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Email");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 25));

        CUSTOMER_AGE.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_AGE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_AGE.setText("NaN");
        CUSTOMER_AGE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_AGE.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Gender");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 25));

        CUSTOMER_L_NAME.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_L_NAME.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_L_NAME.setText("NaN");
        CUSTOMER_L_NAME.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_L_NAME.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Address");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 25));

        CUSTOMER_F_NAME.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_F_NAME.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_F_NAME.setText("NaN");
        CUSTOMER_F_NAME.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_F_NAME.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Contact Number");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("City");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 25));

        CUSTOMER_CONTACT_NUMBER.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_CONTACT_NUMBER.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_CONTACT_NUMBER.setText("NaN");
        CUSTOMER_CONTACT_NUMBER.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_CONTACT_NUMBER.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("NIC Number");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 25));

        CUSTOMER_EMAIL.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_EMAIL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_EMAIL.setText("NaN");
        CUSTOMER_EMAIL.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_EMAIL.setPreferredSize(new java.awt.Dimension(170, 25));

        CUSTOMER_GENDER.setBackground(new java.awt.Color(255, 255, 255));
        CUSTOMER_GENDER.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CUSTOMER_GENDER.setText("NaN");
        CUSTOMER_GENDER.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CUSTOMER_GENDER.setPreferredSize(new java.awt.Dimension(170, 25));

        BACK_BUTTON.setText("Back");
        BACK_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK_BUTTONActionPerformed(evt);
            }
        });

        CUSTOMER_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUSTOMER_IDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CUSTOMER_GENDER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_ID, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CUSTOMER_CONTACT_NUMBER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_NIC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_CITY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_AGE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_L_NAME, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_F_NAME, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_STATUS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_EMAIL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CUSTOMER_ADDRESS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BACK_BUTTON)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BACK_BUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CUSTOMER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_F_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_L_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_CITY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CUSTOMER_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CUSTOMER_CONTACT_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CUSTOMER_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BACK_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK_BUTTONActionPerformed
        dispose();
    }//GEN-LAST:event_BACK_BUTTONActionPerformed

    private void CUSTOMER_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUSTOMER_IDActionPerformed
             try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection)
                DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelSystem", "root", "");
            Statement stmt = con.createStatement();
            
            String sql = "SELECT * FROM Customer WHERE customerId = '"+CUSTOMER_ID.getText()+"' ";
         ResultSet rs = stmt.executeQuery(sql);
       
         while(rs.next()){
         
             
            CUSTOMER_F_NAME.setText(rs.getString(1));
            CUSTOMER_L_NAME.setText(rs.getString(2));
            CUSTOMER_AGE.setText(rs.getString(3));
            CUSTOMER_STATUS.setText(rs.getString(4));
            CUSTOMER_GENDER.setText(rs.getString(5));
            CUSTOMER_ADDRESS.setText(rs.getString(6));
            CUSTOMER_CITY.setText(rs.getString(7));
            CUSTOMER_NIC.setText(rs.getString(8));
            CUSTOMER_CONTACT_NUMBER.setText(rs.getString(9));
            CUSTOMER_EMAIL.setText(rs.getString(10));
                     
         }
                    
         } 
        catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_CUSTOMER_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK_BUTTON;
    private javax.swing.JLabel CUSTOMER_ADDRESS;
    private javax.swing.JLabel CUSTOMER_AGE;
    private javax.swing.JLabel CUSTOMER_CITY;
    private javax.swing.JLabel CUSTOMER_CONTACT_NUMBER;
    private javax.swing.JLabel CUSTOMER_EMAIL;
    private javax.swing.JLabel CUSTOMER_F_NAME;
    private javax.swing.JLabel CUSTOMER_GENDER;
    private javax.swing.JTextField CUSTOMER_ID;
    private javax.swing.JLabel CUSTOMER_L_NAME;
    private javax.swing.JLabel CUSTOMER_NIC;
    private javax.swing.JLabel CUSTOMER_STATUS;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
