package Final_ST2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author kiddabove
 */
public class UpdateEmployee extends javax.swing.JFrame {
    Connection conn = new DBConnection().connect();
    commonFunctions validations = new commonFunctions();

    /**
     * Creates new form UpdateEmployee
     */
    public UpdateEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        OLD_EMPLOYEE_NAME = new javax.swing.JLabel();
        OLD_EMPLOYEE_NIC = new javax.swing.JLabel();
        OLD_EMPLOYEE_DESIGNATION = new javax.swing.JLabel();
        OLD_EMPLOYEE_EMAIL = new javax.swing.JLabel();
        OLD_EMPLOYEE_ADDRESS = new javax.swing.JLabel();
        OLD_EMPLOYEE_CONTACT_NUMBER = new javax.swing.JLabel();
        OLD_EMPLOYEE_USER_NAME = new javax.swing.JLabel();
        OLD_EMPLOYEE_PASSWORD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NEW_EMPLOYEE_NAME = new javax.swing.JTextField();
        NEW_EMPLOYEE_NIC = new javax.swing.JTextField();
        NEW_EMPLOYEE_EMAIL = new javax.swing.JTextField();
        NEW_EMPLOYEE_ADDRESS = new javax.swing.JTextField();
        NEW_EMPLOYEE_CONTACT_NUMBER = new javax.swing.JTextField();
        NEW_EMPLOYEE_USER_NAME = new javax.swing.JTextField();
        NEW_EMPLOYEE_PASSWORD = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        NEW_EMPLOYEE_EID = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Employee details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 0, 280, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Existing Values");

        OLD_EMPLOYEE_NAME.setText("EID");
        OLD_EMPLOYEE_NAME.setPreferredSize(new java.awt.Dimension(150, 30));

        OLD_EMPLOYEE_NIC.setText("EID");
        OLD_EMPLOYEE_NIC.setPreferredSize(new java.awt.Dimension(150, 30));

        OLD_EMPLOYEE_DESIGNATION.setText("EID");
        OLD_EMPLOYEE_DESIGNATION.setPreferredSize(new java.awt.Dimension(150, 30));

        OLD_EMPLOYEE_EMAIL.setText("EID");
        OLD_EMPLOYEE_EMAIL.setPreferredSize(new java.awt.Dimension(150, 30));

        OLD_EMPLOYEE_ADDRESS.setText("EID");
        OLD_EMPLOYEE_ADDRESS.setPreferredSize(new java.awt.Dimension(150, 30));

        OLD_EMPLOYEE_CONTACT_NUMBER.setText("EID");
        OLD_EMPLOYEE_CONTACT_NUMBER.setPreferredSize(new java.awt.Dimension(150, 30));

        OLD_EMPLOYEE_USER_NAME.setText("EID");
        OLD_EMPLOYEE_USER_NAME.setPreferredSize(new java.awt.Dimension(150, 30));

        OLD_EMPLOYEE_PASSWORD.setText("EID");
        OLD_EMPLOYEE_PASSWORD.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_DESIGNATION, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_CONTACT_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(OLD_EMPLOYEE_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(OLD_EMPLOYEE_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OLD_EMPLOYEE_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OLD_EMPLOYEE_DESIGNATION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OLD_EMPLOYEE_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OLD_EMPLOYEE_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OLD_EMPLOYEE_CONTACT_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OLD_EMPLOYEE_USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OLD_EMPLOYEE_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 78, 190, 492);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Employee ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 80, 116, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("New Values");

        NEW_EMPLOYEE_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_EMPLOYEE_PASSWORDActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Admin", "Receptionist" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NEW_EMPLOYEE_EMAIL)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NEW_EMPLOYEE_NAME)
                            .addComponent(NEW_EMPLOYEE_NIC)
                            .addComponent(NEW_EMPLOYEE_ADDRESS)
                            .addComponent(NEW_EMPLOYEE_CONTACT_NUMBER)
                            .addComponent(NEW_EMPLOYEE_USER_NAME)
                            .addComponent(NEW_EMPLOYEE_PASSWORD)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 138, Short.MAX_VALUE))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(NEW_EMPLOYEE_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NEW_EMPLOYEE_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NEW_EMPLOYEE_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NEW_EMPLOYEE_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NEW_EMPLOYEE_CONTACT_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NEW_EMPLOYEE_USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NEW_EMPLOYEE_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(380, 80, 168, 500);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMPLOYEE NAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 180, 101, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIC");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 220, 101, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DESIGNATION");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 270, 101, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMAIL");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 320, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ADDRESS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 370, 101, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PHONE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 420, 101, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("USER NAME");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(230, 470, 101, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PASSWORD");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(230, 510, 101, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("VIEW EXISTING DETAILS & UPDATE");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 600, 240, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("RESET");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 600, 100, 30);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(406, 600, 100, 30);

        NEW_EMPLOYEE_EID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_EMPLOYEE_EIDActionPerformed(evt);
            }
        });
        jPanel1.add(NEW_EMPLOYEE_EID);
        NEW_EMPLOYEE_EID.setBounds(230, 130, 88, 29);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final_ST2/images/updEmp.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, -10, 560, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NEW_EMPLOYEE_EIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_EMPLOYEE_EIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEW_EMPLOYEE_EIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String NA= "N/A";
        validations.setlabelNull(OLD_EMPLOYEE_NAME);
        validations.setlabelNull(OLD_EMPLOYEE_NIC);
        validations.setlabelNull(OLD_EMPLOYEE_DESIGNATION);
        validations.setlabelNull(OLD_EMPLOYEE_EMAIL);
        validations.setlabelNull(OLD_EMPLOYEE_ADDRESS);
        validations.setlabelNull(OLD_EMPLOYEE_CONTACT_NUMBER);
        validations.setlabelNull(OLD_EMPLOYEE_USER_NAME);
        validations.setlabelNull(OLD_EMPLOYEE_PASSWORD);
        
        validations.setTextNull(NEW_EMPLOYEE_NAME);
        validations.setTextNull(NEW_EMPLOYEE_NIC);
        validations.setJComboBoxNull(jComboBox1); 
        validations.setTextNull(NEW_EMPLOYEE_EMAIL);
        validations.setTextNull(NEW_EMPLOYEE_ADDRESS);
        validations.setTextNull(NEW_EMPLOYEE_CONTACT_NUMBER);
        validations.setTextNull(NEW_EMPLOYEE_USER_NAME);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet rs = null;
        String EID = NEW_EMPLOYEE_EID.getText();
        
        String new_name = validations.getTextValue(NEW_EMPLOYEE_NAME);
        String new_nic = validations.getTextValue(NEW_EMPLOYEE_NIC);
        String new_designation = validations.getJComboBoxValue(jComboBox1);
        String new_email = validations.getTextValue(NEW_EMPLOYEE_EMAIL);
        String new_address = validations.getTextValue(NEW_EMPLOYEE_ADDRESS);
        String new_contact = validations.getTextValue(NEW_EMPLOYEE_CONTACT_NUMBER);
        String new_user = validations.getTextValue(NEW_EMPLOYEE_USER_NAME);
        
        
        try{
                if( EID.equals("")){
                     JOptionPane.showMessageDialog(null,"Enter EID");
                   }
                
                else{
                    
                    String query = "SELECT * FROM employee WHERE EID = '"+NEW_EMPLOYEE_EID.getText()+"'";
                    Statement SearchEmployee = conn.createStatement();
                    rs = SearchEmployee.executeQuery(query);
                    
                    
                    //DefaultListModel DLM = new DefaultListModel();
                    
                    if(rs.next()){
                        OLD_EMPLOYEE_NAME.setText(rs.getString(2));
                        OLD_EMPLOYEE_NIC.setText(rs.getString(3));
                        OLD_EMPLOYEE_DESIGNATION.setText(rs.getString(4));
                        //OLD_EMPLOYEE_DOB.setText(rs.getString(10));
                        OLD_EMPLOYEE_EMAIL.setText(rs.getString(8));
                        OLD_EMPLOYEE_ADDRESS.setText(rs.getString(9));
                        OLD_EMPLOYEE_CONTACT_NUMBER.setText(rs.getString(10));
                        OLD_EMPLOYEE_USER_NAME.setText(rs.getString(11));
                        OLD_EMPLOYEE_PASSWORD.setText(rs.getString(12));
                     }
                    else{
                        JOptionPane.showMessageDialog(null,"User not Found");
                    }
                    
                    //cvsdvsdvsdv
                     String updateQuery = "update employee set eName=?,NIC=?,designation=?,email=?,address=?,phone=?,username=? where eid = ?";
                     PreparedStatement updateStatement = conn.prepareStatement(updateQuery);
                     
                     updateStatement.setString(1, new_name);
                     updateStatement.setString(2, new_nic);
                     updateStatement.setString(3, new_designation);
                     updateStatement.setString(4, new_email);
                     updateStatement.setString(5, new_address);
                     updateStatement.setString(6, new_contact);
                     updateStatement.setString(7, new_user);
                     updateStatement.setString(8, EID);

                    if(validations.isEmpty(new_name) ||validations.isEmpty(new_nic) ||validations.isEmpty(new_designation) ||validations.isEmpty(new_email) ||validations.isEmpty(new_address) ||validations.isEmpty(new_contact) ||validations.isEmpty(new_user)){
                        validations.EmptyForm();
                    }
                    else{
                        updateStatement.executeUpdate();
                        JOptionPane.showMessageDialog(null,"User SUCCESSFULLY UPDATED");
                    }
                     
                    
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NEW_EMPLOYEE_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_EMPLOYEE_PASSWORDActionPerformed
         String EID = NEW_EMPLOYEE_EID.getText();
        
        try{
                if( EID.equals("")){
                     JOptionPane.showMessageDialog(null,"Enter EID");
                   }
                
                else{
                    
                    String query = "SELECT * FROM employee WHERE EID = '"+NEW_EMPLOYEE_EID.getText()+"'";
                    Statement SearchEmployee = conn.createStatement();
                    ResultSet rs = SearchEmployee.executeQuery(query);
                    
                    
                    //DefaultListModel DLM = new DefaultListModel();
                    
                    if(rs.next()){
                        OLD_EMPLOYEE_NAME.setText(rs.getString(2));
                        OLD_EMPLOYEE_NIC.setText(rs.getString(3));
                        OLD_EMPLOYEE_DESIGNATION.setText(rs.getString(4));
                        //OLD_EMPLOYEE_DOB.setText(rs.getString(10));
                        OLD_EMPLOYEE_EMAIL.setText(rs.getString(8));
                        OLD_EMPLOYEE_ADDRESS.setText(rs.getString(9));
                        OLD_EMPLOYEE_CONTACT_NUMBER.setText(rs.getString(10));
                        OLD_EMPLOYEE_USER_NAME.setText(rs.getString(11));
                        OLD_EMPLOYEE_PASSWORD.setText(rs.getString(12));
                     }
                    else{
                        JOptionPane.showMessageDialog(null,"User not Found");
                    }
                }
                    
                     }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_NEW_EMPLOYEE_PASSWORDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NEW_EMPLOYEE_ADDRESS;
    private javax.swing.JTextField NEW_EMPLOYEE_CONTACT_NUMBER;
    private javax.swing.JTextField NEW_EMPLOYEE_EID;
    private javax.swing.JTextField NEW_EMPLOYEE_EMAIL;
    private javax.swing.JTextField NEW_EMPLOYEE_NAME;
    private javax.swing.JTextField NEW_EMPLOYEE_NIC;
    private javax.swing.JTextField NEW_EMPLOYEE_PASSWORD;
    private javax.swing.JTextField NEW_EMPLOYEE_USER_NAME;
    private javax.swing.JLabel OLD_EMPLOYEE_ADDRESS;
    private javax.swing.JLabel OLD_EMPLOYEE_CONTACT_NUMBER;
    private javax.swing.JLabel OLD_EMPLOYEE_DESIGNATION;
    private javax.swing.JLabel OLD_EMPLOYEE_EMAIL;
    private javax.swing.JLabel OLD_EMPLOYEE_NAME;
    private javax.swing.JLabel OLD_EMPLOYEE_NIC;
    private javax.swing.JLabel OLD_EMPLOYEE_PASSWORD;
    private javax.swing.JLabel OLD_EMPLOYEE_USER_NAME;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
